---
excludes:
  scopes:
  - pattern: "dev"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."
  - pattern: "lint"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for static code analysis only."
  - pattern: "test"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only."
resolutions:
  rule_violations:
    - message: ".*PyPI::httpx:0\\.25\\.0.*"
      reason: 'CANT_FIX_EXCEPTION'
      comment: 'BSD 3-Clause "New" or "Revised" License: https://github.com/encode/httpx/blob/0.25.0/LICENSE.md'
    - message: ".*PyPI::httpcore:0\\.18\\.0.*"
      reason: 'CANT_FIX_EXCEPTION'
      comment: 'BSD 3-Clause "New" or "Revised" License: https://github.com/encode/httpcore/blob/0.18.0/LICENSE.md'
    - message: ".*PyPI::werkzeug:3\\.0\\.1.*"
      reason: 'CANT_FIX_EXCEPTION'
      comment: 'BSD 3-Clause "New" or "Revised" License: https://github.com/pallets/werkzeug/blob/3.0.1/LICENSE.rst'
    - message: ".*PyPI::numpy:2\\.0\\.0.*"
      reason: 'CANT_FIX_EXCEPTION'
      comment: 'BSD License: https://github.com/numpy/numpy/blob/v2.0.0/LICENSE.txt'