[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
name = "aidial-adapter-bedrock"
version = "0.37.0rc"
description = "DIAL adapter for AWS Bedrock"
authors = [{ name = "EPAM RAIL", email = "SpecialEPM-DIALDevTeam@epam.com" }]
license = "Apache-2.0"
readme = "README.md"
keywords = ["ai"]
classifiers = ["Topic :: Software Development :: Libraries :: Python Modules"]
requires-python = ">=3.11,<4.0"
dynamic = ["dependencies"]

[project.urls]
Homepage = "https://epam-rail.com"
Documentation = "https://epam-rail.com/dial_api"
Repository = "https://github.com/epam/ai-dial-adapter-bedrock/"

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
boto3 = "1.37.24"
botocore = "1.37.24"
aidial-adapter-anthropic = { version = "0.1.0rc0" }
aidial-sdk = { version = "0.28.0", extras = ["telemetry"] }
anthropic = { version = "0.75.0", extras = ["bedrock"] }
fastapi = "0.120.2"
uvicorn = "0.23.2"
pydantic = "1.10.17"
numpy = "2.0.0"
pillow = "10.4.0"

[tool.poetry.group.test.dependencies]
openai = "1.40.0"
pytest-asyncio = "0.21.1"
pytest = "7.4.0"
python-dotenv = "1.0.0"
pytest-dotenv = "^0.5.2"
pytest-xdist = "^3.5.0"
pytest-html = "^4.1.1"
pytest-sugar = "^1.0.0"
pytest-timeout = "^2.3.1"
respx = "^0.22.0"
allure-pytest = "^2.13.5"

[tool.poetry.group.lint.dependencies]
pyright = "1.1.389"
black = "24.3.0"
isort = "5.12.0"
autoflake = "2.2.0"
flake8 = "6.0.0"

[tool.poetry.group.dev.dependencies]
nox = "^2023.4.22"

[tool.pytest.ini_options]
addopts = "-n=auto --asyncio-mode=auto --self-contained-html --html=pytest.html --alluredir=allure-results --timeout=60"
generate_report_on_test = true
env_override_existing_values = 1
testpaths = ["tests"]
filterwarnings = [
  "error",
  # muting warnings like this: ResourceWarning: unclosed <socket.socket fd=13...
  "ignore::ResourceWarning:",
  # muting warnings coming from opentelemetry package
  "ignore::DeprecationWarning:opentelemetry.instrumentation.dependencies",
]

[tool.pyright]
typeCheckingMode = "basic"
reportDeprecated = "error"
reportUnusedVariable = "error"
reportIncompatibleMethodOverride = "error"
exclude = [".git", ".venv", ".nox", "**/__pycache__", "allure-results"]

[tool.black]
line-length = 80
exclude = '''
/(
    \.git
  | \.venv
  | \.nox
  | \.__pycache__
  | allure-results
)/
'''

[tool.isort]
line_length = 80
profile = "black"
skip = [".venv", ".nox", "allure-results"]

[tool.autoflake]
ignore_init_module_imports = true
remove_all_unused_imports = true
in_place = true
recursive = true
quiet = true
exclude = ["\\.venv", "\\.nox", "allure-results"]
