[tool.pyright]
exclude = [
    ".git",
    ".venv",
    "**/__pycache__",
    "bedrock-python-sdk",
]

[tool.black]
line-length = 80
exclude = '''
/(
    \.git
  | \.venv
  | \.__pycache__
  | bedrock-python-sdk
)/
'''

[tool.autoflake]
check = true

[tool.isort]
profile = "black"