name: Cleanup review environment

on:
  pull_request:
    types:
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  cleanup:
    # Only run when PR is actually merged, not just closed
    if: github.event.pull_request.merged == false ### temporary use for not merging
    uses: epam/ai-dial-ci/.github/workflows/cleanup-review-environment.yml@destroy-on-pr-merged
    secrets: inherit
